import pandas as pd
"""
DataFrame 
"""
income = pd.read_csv('income.csv')
print("data type of income ",type(income))

"""
print(income)
print('data shape')
print(income.shape)
print('columns ')
print(income.columns)
print("display first five records")
print(income.head())
print("display last five records")
print(income.tail())
print("display first ten records")
print(income.head(10))
print("display state column data")
print(income.State)
print("alternative way of displaying state column")
print(income['State'])
print("display data of State,Y2002,Y2003")
print(income[['State','Y2002','Y2003']])
print("display every row and column")
print(income.iloc[:,:])
print("display first two rows")
print(income.iloc[:2])
print("displaly rows from index 5 to 10")
print(income.iloc[5:10])
print("display all rows but only two columns")
print(income.iloc[:,:2])
print("display data of State and Y2002 columns")
income.loc[:,["State","Y2002"]]

print("display 10 random records")
print(income.sample(n = 10))
print("diplay 10 % of records")
print(income.sample(frac=.1))
print("data types of columns")
print(income.dtypes)
print("unique record values for index column")
print(income.Index.nunique())
print("frequency distribution")
print(income.Index.value_counts(ascending = True))

print("drop column or row")
print("drop Index column")
income1 =income.drop("Index",axis=1)
print("columns of income1 dataframe")
print(income1.columns)
print("columns of income dataframe")
print(income.columns)
print("inplace to update the income dataframe")
income.drop("Index",axis=1,inplace=True)
print(income.columns)

print("drop a row having index 5")
income.drop(5,axis=0,inplace=True)
print(income.shape)

print("sorting ")
income.sort_values("State",ascending = False)
income.sort_values("State",ascending = False,inplace = True)
incomesorted = income.Y2006.sort_values()
print(incomesorted)
"""
print("Calculating Descriptive Statistics")
print(income.describe())
print("descriptive statistics for Y2005")
print(income.Y2005.describe())
print("Mean - Y2005")
print(income.Y2005.mean())
print("Max ")
print(income.Y2005.max())
print("Sum ")
print(income.Y2005.sum())
print("Aggregate ")
print(income.Y2005.agg(["mean","median"]))
print("group by ")
print(income.groupby("Index")["Y2002"].min())



